export const ADD_ARTICLE = "ADD_ARTICLE";
export const DELETE_ALL_ARTICLES = "DELETE_ALL_ARTICLES";
export const FETCH_DRONES = "FETCH_DRONES";
export const SHOW_ERROR = "SHOW_ERROR";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
